name: CI/CD for Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          settings-path: pom.xml
          working-directory: server
          
      - name: Run Tests
        run: mvn test
        working-directory: server

      - name: Build with Maven
        run: ./mvnw spring-boot:run
        working-directory: server
