name: CI/CD for Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Tests
        run: mvn clean test
        working-directory: server

      - name: Build with Maven
        run: ./mvnw spring-boot:run
