name: CI/CD for Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        maven: [ '3.x']
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
    
      - name: Set up Maven
        run: |
          cd server
          mvn --batch-mode --update-snapshots package
          mvn clean install

      - name: Run Tests
        run: |
          cd server
          mvn test

      - name: Build with Maven
        run: | 
          cd server
          ./mvnw spring-boot:run

