name: CI/CD for Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Navigate to project directory
        run: cd server

      - name: Debug
        run: |
          pwd
          ls -la


      - name: Run Tests
        run: mvn test

      - name: Build with Maven
        run: ./mvnw spring-boot:run
